name: visora
description: visora ai video creator
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0
  url_launcher: ^6.2.5
  provider: ^6.1.2
  path_provider: ^2.1.3
  shared_preferences: ^2.2.3
  video_player: ^2.8.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - assets/fonts/
