workflows:
  visora-workflow:
    name: Visora Build Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build Android
        script: |
          flutter build appbundle --release
      - name: Build Web
        script: |
          flutter build web --release
    artifacts:
      - build/app/outputs/**/*.aab
      - build/web/**
    publishing:
      email:
        recipients:
          - "mantupatra23@gmail.com"
